### ISSUE TITLE
Support for write an OLE document?

### ISSUE THREAD

**Issue by JoseExposito** [catlan/pole#1]
Do you have plans to add support for create an OLE document from their streams or similar?

**Comment by catlan** [comment]
No, I got no plans to do so. But give http://polepp.sourceforge.net a try, the project description states:

POLE++ is a portable C++ library to create read and modify Microsoft OLE compound documents. It is based on POLE library (http://pole.berlios.de) created by Ariya Hidayat (ariya@kde.org).
